### PR TITLE
Create firebase auth provider for Guard

### PR DESCRIPTION
**Pull request by josefkarasek**
Follow the pattern of other providers are created.

One new command line argument:
    --firebase.sa-json-file - path to the google service account json file

This file is already used by the google provider, but I was getting
conflict issues when I tried to reuse this switch.

### CODE REVIEW

**Comment by josefkarasek** [comment]
Remaining work:
[*] unit tests

**Comment by josefkarasek** [comment]
Usage - create and download new Service Account at https://console.cloud.google.com/iam-admin/serviceaccounts and use guard to generate k8s manifests:
```
$ guard get installer --auth-providers=firebase \
  --firebase.sa-json-file=/Users/jkarasek/ddev-live-preprod-ca85172a8299.json > installer.yaml
```
Deploy these resources:
```
kubectl apply -f installer.yaml
```

**Comment by dclear** [comment]
don't forget CLA signing @josefkarasek - https://github.com/drud/guard/pull/1#issuecomment-505940498

**Comment by dclear** [comment]
the call on planning was -- after Josef add a couple more commits -- to go ahead and see if we can merge this despite the CLA warning...he has signed it.

**Comment by wozniakjan** [comment]
@josefkarasek @jrthrawny I managed to resolve the dependencies for firebase and pushed to this branch as latest commit. It builds and seems to work well. Also changed the user info provided back from firebase to contain the email in authentication TokenReview in https://github.com/josefkarasek/guard/pull/1.

**Comment by dclear** [comment]
Let merge this bad boy CET :)

**Pull request merged**
